Name <- c("Swarup", "Amit", "Priya")
Age <- c(20, 21, 19)
Gender <- c("Male", "Male", "Female")
Marks <- c(96, 92, 94)
student <- data.frame(Name, Age, Gender, Marks)
cat("The data frame :- \n")
print(student)
cat("The data frame structure :- \n")
str(student)